- extensions/ExpansionCardPackage.lua
修改【奇正相生】on_use 为基类方法，以处理结算问题
Fixes #591 
> fix: 修正【奇正相生】结算问题

- lua/ai/ExpansionPackage-ai.lua
修正 AI 对【双雄】处理，将 mark 切换为 flag，并修正选色逻辑
Fixes #587 
> fix: 修正【双雄】AI

- lua/QSanguoshaLuaFunction.lua
> fix: 修正【凌人】偶发中断 bug

- extensions/GroupFriendPackage.lua
> fix: 修正【亡命】中伤害结构体

- lua/ai/ExpansionPackage-ai.lua
> fix: 修正【狼袭】AI 选人逻辑

- extensions/ExpansionPackage.lua
> fix: 修正【椎锋】可选目标

- audio/skill/ExMouSunshangxiang.ogg
- audio/skill/LuaMouJieyin1.ogg
- audio/skill/LuaMouJieyin2.ogg
- audio/skill/LuaMouLiangzhu1.ogg
- audio/skill/LuaMouLiangzhu2.ogg
- audio/skill/LuaMouXiaoji1.ogg
- audio/skill/LuaMouXiaoji2.ogg
- extensions/ShieldPackage.lua
- image/fullskin/generals/full/ExMouSunshangxiang.png
- image/generals/card/ExMouSunshangxiang.jpg
- image/mark/@LuaMouLiangzhu.png
- lang/zh_CN/Audio/ShieldPackageLines.lua
- lang/zh_CN/Package/ExpansionPackage.lua
- lang/zh_CN/Package/ShieldPackage.lua
- lua/ai/ShieldPackage-ai.lua
> feat: 添加谋孙尚香

- extensions/ExpansionPackage.lua
> fix: 修正【谦冲】距离限制有效时间

- extensions/ExpansionPackage.lua
- extensions/GroupFriendPackage.lua
- lua/QSanguoshaLuaFunction.lua
> refactor: 修正转换牌系列问题

- extensions/LandlordsPackage.lua
- lua/QSanguoshaLuaFunction.lua
> fix: 修正斗地主手气卡问题

- image/mark/@LuaPingding.png
- image/mark/@baoli.png
- image/mark/@luashanjia.png
- image/mark/@wuku.png
> fix: 移除标记左下角阴影

- lua/ai/StrategicAttackShacklePackage-ai.lua
> fix: 修正谋于禁【节钺】给牌 AI

- extensions/LayingPlansSincerityPackage.lua
> fix: 修正神太史慈【神著】标记处理问题

- extensions/StrategicAttackPreviewPackage.lua
> fix: 修正【反间】流程

- extensions/LayingPlansCouragePackage.lua
> fix: 修正宗预【御严】失效问题

- lua/ai/LayingPlansWisdomPackage-ai.lua
> fix: 修正神郭嘉【佐幸】 AI 抽风问题

- .gitignore
- audio/skill/ExTenYearShenJiangwei.ogg
- audio/skill/LuaJiufa1.ogg
- audio/skill/LuaJiufa2.ogg
- audio/skill/LuaPingxiang1.ogg
- audio/skill/LuaPingxiang2.ogg
- audio/skill/LuaTianren1.ogg
- audio/skill/LuaTianren2.ogg
- extensions/DevineForcePackage.lua
- extensions/ExpansionPackage.lua
- image/fullskin/generals/full/ExTenYearShenJiangwei.png
- image/generals/card/ExTenYearShenJiangwei.jpg
- image/mark/@LuaJiufa.png
- image/mark/@LuaPingxiang.png
- image/mark/@LuaTianren.png
- lang/zh_CN/Audio/DevineForcePackageLines.lua
- lang/zh_CN/Package/DevineForcePackage.lua
> feat: 添加神姜维

- lua/QSanguoshaLuaFunction.lua
> fix: 修正文本缺失

- extensions/DevineForcePackage.lua
> fix: 修正【九伐】类型判断问题

- audio/skill/ExMouXiahoushi.ogg
- audio/skill/LuaMouQiaoshi1.ogg
- audio/skill/LuaMouQiaoshi2.ogg
- audio/skill/LuaMouYanyu1.ogg
- audio/skill/LuaMouYanyu2.ogg
- extensions/ExpansionPackage.lua
- extensions/StrategicAttackTogetherPackage.lua
- image/fullskin/generals/full/ExMouXiahoushi.png
- image/generals/card/ExMouXiahoushi.jpg
- lang/zh_CN/Audio/StrategicAttackTogetherPackageLines.lua
- lang/zh_CN/Package/StrategicAttackTogetherPackage.lua
- lua/QSanguoshaLuaFunction.lua
- lua/ai/StrategicAttackTogetherPackage-ai.lua
1. 添加新武将谋夏侯氏
2. 修正曹婴凌人代码中未引用变量问题
Fixes #674 
> feat: 添加谋夏侯氏

- extensions/LandlordsPackage.lua
- lua/QSanguoshaLuaFunction.lua
> fix: 调整斗地主模式势力选择时机

- lua/ai/ExpansionPackage-ai.lua
> fix: 修正 AI 不发动【峻刑】问题

- extensions/LayingPlansWisdomPackage.lua
- lua/QSanguoshaLuaFunction.lua
> fix: 调整从牌堆拿牌效果

- extensions/LayingPlansCouragePackage.lua
修正 obtainCard 方法对应参数为 card 而非 id
> fix: 修正王双不能获取其他人装备问题

- image/mark/@LuaQinzheng.png
- lua/QSanguoshaLuaFunction.lua
1. 调整勤政获取牌，移除从弃牌堆获取牌的情况
2. 调整勤政记录标记
> fix: 【勤政】不再从弃牌堆获取牌，调整记录标记

- .github/workflows/email-notification.yml
> ci: Draft PR 不再触发邮件通知流程

- extensions/DevineForcePackage.lua
- extensions/ExpansionPackage.lua
- extensions/GroupFriendPackage.lua
- extensions/LayingPlansCouragePackage.lua
- extensions/LayingPlansSincerityPackage.lua
- extensions/LayingPlansWisdomPackage.lua
- extensions/StrategicAttackAbilityPackage.lua
- extensions/StrategicAttackKnowledgePackage.lua
- extensions/StrategicAttackPreviewPackage.lua
- extensions/StrategicAttackShacklePackage.lua
- extensions/StrategicAttackTogetherPackage.lua
> fix: 调整技能卡显示信息

- extensions/LayingPlansSincerityPackage.lua
> fix: 修正【合击】表现

- lua/QSanguoshaLuaFunction.lua
> fix: 修正护甲导致的闪退问题

- extensions/LayingPlansSincerityPackage.lua
> fix: 修正【合击】距离限制

- extensions/LayingPlansWisdomPackage.lua
- lua/QSanguoshaLuaFunction.lua
> fix: 修正获取牌

- extensions/StrategicAttackPreviewPackage.lua
> fix: 修正谋曹操【奸雄】无标记依然询问是否移除问题

- lua/ai/ExpansionPackage-ai.lua
> fix: 调整星徐晃【治严】AI

- extensions/ExpansionPackage.lua
- image/fullskin/generals/full/JieGongsunzan.png
- image/generals/card/JieGongsunzan.jpg
- image/heroskin/generals/card/caoang_1.jpg
- lang/zh_CN/Package/ExpansionPackage.lua
> feat:添加手杀界公孙瓒，顺便改曹昂皮肤

- .github/workflows/auto-release.yml
> ci: 发布 tag 自动打包并 release

- .github/workflows/auto-release.yml
优化打包发布流程，将 lfs 文件纳入打包范围中
Fixes #720 
> ci: 重新调整自动打包 workflow 流程

- README.md
> docs: 添加潘濬【观微】修正指南

- extensions/ExpansionPackage.lua
- extensions/PuyuanEquipCardPackage.lua
1. 修正蒲元武器移出游戏问题
2. 处理偶发马良自书 nil 报错
Fixes #730 
> fix: 系列 bug 修正

- extensions/ExpansionPackage.lua
> fix: 修正界祝融性别与巨象 bug

- extensions/RectificationPackage.lua
- lua/QSanguoshaLuaFunction.lua
> refactor: 优化整肃成功部分

- extensions/ExpansionPackage.lua
> fix: 修正【秉清】失效问题

- extensions/LayingPlansSincerityPackage.lua
- extensions/LayingPlansWisdomPackage.lua
- extensions/PrayFortunePackage.lua
- extensions/StrategicAttackPreviewPackage.lua
1. 修正重构后部分引用错误
2. 修正谋曹操【奸雄】询问移除【治世】标记条件
> fix: 技能与引用修正

- extensions/OLBoundaryBreachStandardPackage.lua
修正 OL 界赵云【涯角】无攻击范围内有其角色时，展示框不消失问题
Fixes #769 
> fix: 修正【涯角】展示框不消失问题

- extensions/StrategicAttackShacklePackage.lua
> fix: 修正【烈弓】显示问题

- extensions/ShieldPackage.lua
修正【巨象】【祸首】非锁定技失效问题
Fixes #790 
> fix: 修正【巨象】【祸首】非锁定技失效问题

- .gitignore
- audio/skill/chenghao1.ogg
- audio/skill/chenghao2.ogg
- audio/skill/jianjie1.ogg
- audio/skill/jianjie2.ogg
- audio/skill/jianjie3.ogg
- audio/skill/simahui.ogg
- audio/skill/yinshi1.ogg
- audio/skill/yinshi2.ogg
- extensions/extra.lua
> fix: 修正司马徽【隐士】问题

- audio/skill/JieWolong.ogg
- audio/skill/LuaBazhen1.ogg
- audio/skill/LuaBazhen2.ogg
- audio/skill/LuaCangzhuo1.ogg
- audio/skill/LuaCangzhuo2.ogg
- audio/skill/LuaHuoji1.ogg
- audio/skill/LuaHuoji2.ogg
- audio/skill/LuaKanpo1.ogg
- audio/skill/LuaKanpo2.ogg
- extensions/ExpansionPackage.lua
- lang/zh_CN/Audio/ExpansionPackageLines.lua
> feat: 增补界卧龙诸葛语音

- extensions/extra.lua
> fix: 修正司马徽【称好】问题

- README.md
调整 Readme.md 里补充说明内容：
- 增加“关于禁用源码级别的包”指南 
> docs: 更新 Readme

- extensions/LandlordsPackage.lua
- lang/zh_CN/Package/ExpansionPackage.lua
- lua/QSanguoshaLuaFunction.lua
1. 修正斗地主调整初始血量时触发技能问题
2. 调整杨仪技能文本
Fixes #848 
> fix: 斗地主 Bug 与技能提示文本修正

- extensions/LandlordsPackage.lua
修正斗地主首个回合某些技能未触发问题
Fixes #861 
> fix: 修正斗地主角色当前【回合开始时】技能未触发问题

- extensions/ExpansionPackage.lua
- extensions/PuyuanEquipCardPackage.lua
- lua/QSanguoshaLuaFunction.lua
调整部分涉及到判定的技能，使得 AI 能判断是否改判
技能列表：
1. 马元义【兵祸】
2. 装备【天雷刃】
Fixes #864 
> fix: 修正简单的 AI 判定

- extensions/CountryAsBeforeElucidationPackage.lua
- image/mark/@LuaGuanjue-Club-Clear.png
- image/mark/@LuaGuanjue-Diamond-Clear.png
- image/mark/@LuaGuanjue-Heart-Clear.png
- image/mark/@LuaGuanjue-Spade-Clear.png
> fix: 承·关羽【冠绝】标记可视化

- extensions/ExpansionPackage.lua
> fix: 调整【让节】语音播放和技能文字提示

- extensions/LayingPlansCouragePackage.lua
- lua/ai/ExpansionPackage-ai.lua
修正界陈群【定品】技能对于自书类技能的判断
Fixes #873 
> fix: 修正界陈群【定品】AI

- extensions/CountryAsBeforeIntroductionPackage.lua
> fix: 修正起·刘备【振鞘】问题

- extensions/BraveWarriorsPackage.lua
修正十周年留赞【力激】不能弃置装备牌的问题
Fixes #885 
> fix: 修正十周年留赞【力激】不能弃置装备牌的问题

- extensions/ExpansionPackage.lua
以禁止选择相同 id 卡牌临时规避界夏侯惇【清俭】重复牌问题
Fixes #898 
> fix: 修正界夏侯惇【清俭】重复牌问题

- extensions/ExpansionPackage.lua
- image/mark/@LuaJuetaoMark.png
- lang/zh_CN/Package/ExpansionPackage.lua
> fix: 追补【决讨】限定标图片

- extensions/GroupFriendPackage.lua
> fix: 修正励行导致的重复结算问题

- extensions/RectificationPackage.lua
修正整肃虚拟牌结算规则，虚拟卡牌使用不再介入整肃【擂进】【变阵】结算
Fixes #908 
> fix: 修正整肃虚拟牌结算规则

- extensions/LayingPlansSincerityPackage.lua
调整神孙策“冯河”扣减体力上限步骤在给牌之前
Fixes #912 
> fix: 调整“冯河”扣减体力上限在给牌之前

- extensions/GoodMatchPackage.lua
增补“凶疑”主副将变更逻辑，主要根据孙翊所在主副将位置变更，其次处理特殊场景
Fixes #911 
> fix: 增补“凶疑”主副将变更逻辑

- extensions/ExpansionPackage.lua
> fix: 修正界公孙瓒“义从”计算距离问题

- .github/ISSUE_TEMPLATE/new_skin.md
> docs: 新皮肤 issue 模板

- image/heroskin/audio/JieJushou_1/death/JieJushou.ogg
- image/heroskin/audio/JieJushou_1/skill/LuaJianying1.ogg
- image/heroskin/audio/JieJushou_1/skill/LuaJianying2.ogg
- image/heroskin/audio/JieJushou_1/skill/LuaShibei1.ogg
- image/heroskin/audio/JieJushou_1/skill/LuaShibei2.ogg
- image/heroskin/fullskin/generals/full/JieJushou_1.png
- image/heroskin/generals/card/JieJushou_1.jpg
- image/heroskin/lang/zh_CN/Audio/StandardGeneralPackageLines.lua
复用沮授皮肤资源，界沮授【初冬观雪】皮肤
Fixes #942 
> feat: 界沮授【初冬观雪】皮肤

- .github/workflows/auto-release.yml
- .github/workflows/email-notification.yml
- .github/workflows/lua-check.yml
Security CodeQL 扫描指出 actions 应该限制对应的权限，调整工作流权限
Fixes #968 
> ci: 调整工作流权限

- extensions/ExpansionPackage.lua
> fix: 修正战烈选择提示发起人

- README.md
> docs: 调整 Readme 语序

- extensions/MartialTemplePackage.lua
手动规避“雄幕”【白银狮子】卸载不生效问题
Fixes #995 
> fix: 手动规避“雄幕”【白银狮子】卸载不生效问题
