extensions/ShieldPackage.lua
=> fix: 修正有护甲状态下直接受伤害濒死的显示信息

extensions/StrategicAttackShacklePackage.lua
修正谋黄盖【诈降】优先级结算导致的【万箭齐发】可以被卧龙诸葛亮【八阵】响应的问题
=> fix: 调整谋黄盖【诈降】结算优先级

extensions/ExpansionPackage.lua, lua/ai/ExpansionPackage-ai.lua
调整界李儒【灭计】弃牌逻辑，只有一张非基本牌时弃置后不需要继续询问
=> fix: 调整界李儒【灭计】弃牌逻辑

extensions/ExpansionPackage.lua
修正青钢剑杀审配触发【守邺】失效后装备失效问题
Fixes #658 
=> fix: 修正【守邺】对青钢标记的处理

extensions/LandlordsPackage.lua
=> fix: 修正斗地主初始摸牌触发武将技能问题

extensions/LayingPlansCouragePackage.lua, lang/zh_CN/Package/LayingPlansCouragePackage.lua
=> fix: 文鸯【椎锋】失效期限修正

extensions/LayingPlansSincerityPackage.lua
调整 pattern 为【决斗】时首字母大写
Fixes #693 
=> fix: 修正【合计】选择【决斗】时 pattern 不正确的问题

extensions/LayingPlansSincerityPackage.lua
=> fix: 调整【合击】目标不能为自己

extensions/LayingPlansSincerityPackage.lua
1. 修正神太史慈多次摸三张牌不能在新的自己回合出杀问题
2. 添加神太史慈破围头像技能文字效果
=> fix: 修正神太史慈【神著】多次选择二选项后新回合不能出杀问题

extensions/PuyuanEquipCardPackage.lua
修正蒲元武器在死亡后进入弃牌堆时不正确问题
Fixes #730 
=> fix: 修正死亡后移出游戏

extensions/ExpansionPackage.lua, extensions/StrategicAttackTogetherPackage.lua
1. 修正谋孙策激昂摸牌数量问题
2. 修正星魏延骜肆标记清理问题
Fixes #796 
=> fix: 修正谋孙策【激昂】多目标摸牌问题

extensions/ExpansionPackage.lua, extensions/GroupFriendPackage.lua, extensions/LayingPlansSincerityPackage.lua
修正取消目标技能重复判定问题，包含如下技能
- 阿杰【嘉人】
- 神太史慈【笃烈】
Fixes #837 
=> fix: 修正取消目标技能重复判定问题

extensions/LayingPlansSincerityPackage.lua
调整神太史慈【破围】移动标记时机到回合开始时
Fixes #888 
=> fix: 调整神太史慈【破围】移动标记时机

extensions/ImpassePackage.lua
修正回合内触发“大吉”导致锦囊失效的问题
Fixes #916 
=> fix: 修正回合内触发“大吉”无效锦囊的问题

extensions/DevineForcePackage.lua
修正神张飞“巡使”响应使用无色牌场景不记录的问题，如八卦阵使用的无色闪
Fixes #920 
=> fix: 修正神张飞“巡使”响应使用无色牌场景不记录的问题

lua/QSanguoshaLuaFunction.lua, lua/ai/ExpansionPackage-ai.lua
修正毅谋 AI 与 Table 打乱起始下标错误问题
1. 毅谋 AI 代码使用了两次随机，删去第一次的打乱顺序
2. Table shuffle 公共方法中使用 0 作为起始下标，修改为 1
Fixes #926 
=> fix: 修正毅谋 AI 与 Table 打乱起始下标错误问题

extensions/StrategicAttackTogetherPackage.lua, extensions/UniteEffortsPackage.lua
1. 调整协力对外暴露接口
2. 协力增加即时成功判断逻辑
Fixes #918 
=> fix: 协力增加即时成功判断逻辑

extensions/ExpansionPackage.lua
调整杨彪义争发动 enabled_at_play 判断条件，移除提前判断其他角色部分
Fixes #935 
Fixes #936 
=> fix: 调整杨彪“义争”按钮亮起条件

extensions/GatheringHeroesFarAwayJianghuPackage.lua
=> fix: 修正管宁“遁世”摸牌数量错误问题

extensions/GatheringHeroesXuzhouPackage.lua
修正礼赂给牌限制，移除最高为 5 的限制
Fixes #960 
=> fix: 修正礼赂给牌限制

extensions/ExpansionPackage.lua, lua/QSanguoshaLuaFunction.lua
调整花色转换数字函数，以修正渐营对使用无花色摸牌触发条件
Fixes #963 
=> fix: 修正界沮授渐营花色判断条件

extensions/ExpansionPackage.lua
修正“守邺”对延时锦囊牌的处理，即时回收延时锦囊牌
Fixes #962 
=> fix: 修正“守邺”对延时锦囊牌的处理

extensions/ExpansionPackage.lua
修正势太史慈“酣战”和“战烈”部分情况下不显示技能名提示问题
Fixes #966 
=> fix: 修正势太史慈“酣战”和“战烈”部分情况下不显示技能名提示问题

extensions/ExpansionPackage.lua, lua/ai/ExpansionPackage-ai.lua
1. 修正势太史慈 AI 默认选择战烈不弃牌问题
2. 修正审配守邺发动 AI，默认队友用牌不发动
3. 调整战烈失去标记时机
Fixes #971 
=> fix: 修正势太史慈和审配 AI

extensions/ExpansionPackage.lua, lang/zh_CN/Package/ExpansionPackage.lua
势太史慈技能选择后提示增补，将战烈、振锋的选项显示出来
Fixes #973 
=> fix: 势太史慈技能选择后提示增补

extensions/LandlordsPackage.lua, lua/ai/LandlordsPackage-ai.lua
叫分后移除小于等于的叫分选项，例如叫了 2 分之后，移除 1 分和 2 分选项
Fixes #979 
=> fix: 叫分后移除小于等于的叫分选项

extensions/ExpansionPackage.lua, extensions/GroupFriendPackage.lua
饿人类“寻衅”技能适配【朱雀羽扇】
1. 在装备朱雀羽扇后，因“寻衅”出【杀】前，若装备【朱雀羽扇】则会先提示是否发动，若发动则改为火【杀】，不发动也不会再次询问
2. 为装备【朱雀羽扇】场景下出火【杀】添加动画
Fixes #987 
=> fix: 饿人类“寻衅”技能适配【朱雀羽扇】

extensions/OldFriendPackage.lua
调整侠行获取【玄剑】逻辑，移除原有结构体中玄剑的卡牌 id，避免重复弃置
Fixes #1013 
=> fix: 调整侠行获取【玄剑】逻辑，移除原有结构体中玄剑的卡牌 id，避免重复弃置
